### ISSUE TITLE
duplicate entry shouldn't get added to metadata twice

### ISSUE THREAD

**Issue by joehand** [holepunchto/hyperdrive#107]
If the same file, with the same content + metadata, is added twice, it shouldn't be added to the metadata twice. 

Happening in [the CLI](https://github.com/datproject/dat/issues/542). We can fix it there, but it seems like we should also protect against this in hyperdrive.

**Comment by mafintosh** [comment]
Unsure about this. I'm leaning towards "just dont do that" as checking if a file already exists has none trivial perf overhead (needs hashing)

**Comment by pfrazee** [comment]
Yeah I suggest we check the hash against current and noop if it's not a change. Then we add an option flag, `allowDuplicate` or something like that, which if true will skip the hash check.

**Comment by juliangruber** [comment]
Hashing will impose a _significant_ overhead. While more correct, we might still get better results with just "overwriting" with the identical, no?

**Comment by pfrazee** [comment]
The hashing will occur in either situation, won't it? You have to hash any new writes to the hypercore
