### ISSUE TITLE
add path normalization

### ISSUE THREAD

**Issue by juliangruber** [holepunchto/hyperdrive#112]
As mentioned in https://github.com/juliangruber/hyperdrive-import-files/pull/23#issuecomment-253499239, it would make sense to me to fully treat `entry.name` as a path and thus also apply normalisation if necessary. Currently it's only treated as a `String`, and eg there could be two entries `/entry` and `./entry`. This should help the modules depending on this to simplify their path logic.

**Comment by mafintosh** [comment]
great idea. do you know a module that helps with this?

**Comment by juliangruber** [comment]
this seems to work well:

```js
const normalize = p => path.resolve('/', p)
```

Normalizes like this:

- `/` -> `/`
- './foo' -> `/foo`
- `foo/bar` -> `/foo/bar`
- `foo/bar/` -> `/foo/bar/`

**Comment by mafintosh** [comment]
Cool. In addition to that it should normalize windows paths to unix ones. `\` --> `/`
