### ISSUE TITLE
Using dat with the http option has problems with syncing (deletion)

### ISSUE THREAD

**Issue by beingalink** [holepunchto/hyperdrive#171]
Steps to reproduce:

1. Add a folder on the master
2. Visit the folder in the browser and open one or more files in the browser (index.html or pdf files)
3. Delete the folder in master
4. The metadata syncs correctly and the folder is removed in the browser view but it's still there in the file system of the client's host (containing the files that were opened in the browser)

**Comment by beingalink** [comment]
This problem doesn't seem to occur anymore. Don't know when it got fixed though.

**Comment by beingalink** [comment]
OK, I just stumbled across this issue again. Seems like it's still there.

**Comment by creationix** [comment]
@beingalink are you on Linux or OSX?

**Comment by beingalink** [comment]
@creationix The server is on linux (centos 7) and the client on os x.

**Comment by creationix** [comment]
Nevermind, I misunderstood the question.  I've seen a case where FS changes aren't detected at all and never get into the source dat.  This seems worse on linux.
