### ISSUE TITLE
archive.key does not get set if you pass in content

### ISSUE THREAD

**Issue by joehand** [holepunchto/hyperdrive#175]
If you pass in `content` as an option, the archive.key [never gets set](https://github.com/mafintosh/hyperdrive/blob/master/index.js#L696). May also be fixed with #149. 

I can PR test for this. Seems like it'd be an easy fix moving the self.key above cb in line linked, but not sure if there is another constraint I'm missing.

**Comment by mafintosh** [comment]
No it's prob that easy :) Go for it
