### ISSUE TITLE
proxy content from sparse archive to peer

### ISSUE THREAD

**Issue by joehand** [holepunchto/hyperdrive#194]
(opening for discussion + posterity since I keep forgetting this)

We want to proxy archives from a server to a remote peer that may not be able to connect to the swarm (for instance, a browser peer connected via websockets):

As far as I remember, this is what @mafintosh suggested:

* Set up server to listen to `onwant` requests
* Download requested content, then respond to onwant

It'd be cool to have this as an api or module we can use. This may also relate to remote storage, for example with [dat-http](https://github.com/datproject/dat-http).

**Comment by creationix** [comment]
Another idea I have is to create a way to proxy the archive interface directly using some form of RPC (think dnode).  I'd have to see exactly what subset of the interface I'd need to proxy and what the performance implications of that route are.

**Comment by pfrazee** [comment]
Bear in mind that Beaker uses a different API than hyperdrive

**Comment by creationix** [comment]
@pfrazee yep, I have several concurrent concepts I'm trying to prove out, not all of them involve cloning the beaker environment in https sites.
