### ISSUE TITLE
State of multiwriter?

### ISSUE THREAD

**Issue by aral** [holepunchto/hyperdrive#230]
I was just wondering what the state of multiwriter support is in Hyperdrive currently. I see that the last work on multiwriter was around four months ago.

Is it still within the near-term roadmap to integrate multiwriter into mainline hyperdrive and DAT CLI?

**Comment by RangerMauve** [comment]
I think @jimpick has been working on it in his spare time. He's got a fork with the latest and greatest changes somewhere.

**Comment by pfrazee** [comment]
It is still being worked on! @mafintosh has been steadily finalizing it while also working on the new discovery code. Jim has also been building out those test demos, as Ranger says.

**Comment by Frando** [comment]
It would be great if the changes by @jimpick could be pulled in. I didn't go through all of them, @jimpick would you do a PR to here? Or is there still experimental stuff in your branch?

It had some fixes that I needed so I started from there for some patches, which I could also try to rebase on @mafintosh's branch but wouldn't do that if not needed.

**Comment by jimpick** [comment]
It's still pretty experimental... the last month has been very busy with travel and holidays, so apologies if it all seems stalled.

There are a lot of hacks in there to get it to work as much as it does, so it's not really production quality.

I've noticed that with multiwriter, when things don't work, it often results in deleted files, so it's probably not a good idea to just release the changes "into the wild" without a lot of review and discussion.

I gave a talk in Tokyo where I showed the Dat multiwriter command line interacting with a version of dat-shopping-list (with updated dependencies). I had to make a few quick fixes for that to work... the latest commit is here:

https://github.com/jimpick/hyperdrive/commit/a2648fbdef84041cc78b7d1efe5c92c407895242

Here are the slides from my talk:

https://tokyo-dat.jimpick.com/

If I can find some time in the next month, I really should write that up into a blog post.

I had previously talked with @joehand about possibly releasing the pre-release version using his dat-next npm package.

**Comment by aral** [comment]
@jimpick What are your thoughts on multiwriter vs multi-feed?

(I see them as complimentary: multiwriter for the use case of a person authorising additional devices for their master feed and multi-feed for “conversations” between different people.)

Would be great to perhaps get a small working group together to scope this out. I’d love to be involved with this as it’s central to what I’m building.

CC @noffle

**Comment by jimpick** [comment]
Multifeed is really useful when you want to replicate multiple feeds over a single replication stream. I actually built something very similar inside hypermerge (I was inspired by what hyperdb did internally). Hyperdb (and multiwriter) could probably even use it internally to manage the hypercores it replicates...

**Comment by karissa** [comment]
Hey all, @mafintosh and @andrewosh just put out a new multiwriter release candidate, 11 days ago:
https://github.com/mafintosh/hyperdrive/blob/3877eec49e6c0244b0df62d57cbc9e57b4d9224e/README.md

Time to try it out and give feedback or improve it. Really excited to see this roll out this year.

**Comment by aral** [comment]
This is so exciting; can’t wait to try it out (just working to finalise Indie Web Server, one of the core components of Hypha so the timing is perfect). Thank you for the heads up, @karissa :)

**Comment by 100ideas** [comment]
@aral last year  @jimpick experimentally patched `hyperdrive` to support `hyperdb + multiwriter` storage. He published it as a package on npm,  '@jimpick/hyperdrive-next'. I *think* the patched source code is here: https://github.com/jimpick/hyperdrive/tree/multiwriter-staging

I was curious about the potential to use dat + hyperdrive to create bidirectional filesystem synching between server & web app, so I made a little prototype: https://github.com/100ideas/hypercore-protocol-proxy-test

Its outdated by a year but it does show how to get duplex replication + synching set up between a dat archive on a server and a dat archive in the browser over a private websocket connection.

Also, while looking up some of these links, I came across @karissa's `peerfs` experiment, which was last updated may 2019 and is described as "multiwriter peer-to-peer filesystem, built on kappa-core and hyperdrive". It looks like it uses more recent (kappa) approaches to setting up multi-hyperdrive. https://github.com/karissa/peerfs.

Lastly these two tutorials show the way for setting up private key exchange for multiwriter situations and explain kappa architecture a bit better. (I haven't been paying attention to dat for the last year so I found them informative, apologies if they are well known already)
- https://geut.github.io/dat-workshop/#/problems/08/ (multiwriter hyperdb for key exchange channel)
- https://kappa-db.github.io/workshop/build/08.html (shows [multifeed](https://github.com/noffle/multifeed))

**Comment by aral** [comment]
Thanks @100ideas :) I’m still wondering if there’s a definitive timeline for multiwriter support in DAT. I don’t want to try and implement my own version only to find that it’s incompatible with DAT in the future. I know @mafintosh stated he was working on this in March.

**Comment by RangerMauve** [comment]
From what I understand, @mafintosh and hyperdivision got a contract to work on multiwriter by December. And it looks like their current path towards that is called "union mounts". Before that though, they'll be working on a system that enables you to [share a secret key between devices with a third party service for coordinating writes](https://github.com/datproject/planning/#third-party-services-to-make-it-safe-to-transfer-a-hypercore-across-devices).

**Comment by alterx** [comment]
Good afternoon folks,

I've been looking into a fully decentralized option to build applications (I've also looked into textile.io, GunDB, and SSB) and so far Dat seems pretty close to what I need. I've been following its development for a long time and multi-writer is something that I think will give Dat the upper-hand over other technologies such as SSB. 

With that being said, I've found several packages that claim to achieve multi-writer capabilities on top of Dat. Specifically, I'm talking about [kappa-drive](https://ledger-git.dyne.org/CoBox/kappa-drive) (previously known as peerfs) and [hyperdb](https://github.com/mafintosh/hyperdb). While these seem like viable architectures it's very difficult to know if they're going to be part of the "main" Dat "stack". It feels like there's little information about what's the state of multi-writer, what's the "official" solution (if any), etc. I understand that this is a project with limited resources (both time and monetary) but I can't shake off the feeling that communication around this feature (which I feel is crucial to driving mainstream adoption) hasn't been great, leading to some confusion around it.

**Comment by noffle** [comment]
@alterx My impression has been that "multiwriter" has a broad solution space, depending on your needs. I don't think there's an "official" solution?

- If you want a filesystem abstraction, `hyperdrive` or `kappa-drive` are good options.
- If you want a general-purpose p2p database, `kappa-core` is a good choice.
- [hypermerge](https://github.com/automerge/hypermerge) is another approach for multiwriter p2p programs.
- [cabal-core](https://github.com/cabal-club/cabal-core) if you want a p2p chat database.
- etc

There have been lots of different ways to build on top of `hypercore`, the base append-only log abstraction. They are all legitimate solutions to multiwriter problem, each with their own communities. "Official" is kinda a weird thing, since whatever direction, e.g. hyperdrive goes in, the other modules that don't depend on hyperdrive will continue to exist and grow too, whether it bears the Dat logo or not.

Short answer: pick a solution that meets your needs! They won't vanish or stop being useful after hyperdrive picks a multiwriter approach. :)

**Comment by alterx** [comment]
@noffle I still think I'll wait for whatever `hyperdrive` ends up doing (it feels like it will probably be flexible enough to support most of the use cases you mentioned). Your answer really clears thing up for me though :), thanks!

**Comment by mriise** [comment]
It really would be preferable to wait for hyper protocol to make an implementation that allows multiple writers with their signature so that you can track that "publicKey made X change". In reality, I'm not sure if that's actually part of the plan... Either way, I think it's worthwhile to wait and see what they do.

**Comment by okdistribute** [comment]
@mriise check out https://github.com/kappa-db

**Comment by mriise** [comment]
@okdistribute thanks! I had looked at it earlier and it seemed a bit too much for what I had in mind. A simpler solution I came across (in one of @pfrazee 's templates) is to just use drive mounting to aggregate user data (and it allows users to own their data).

**Comment by jalcine** [comment]
Bumping this because I have an interest in using Hyperdrivers as a storage layer for [my project](https://koype.net)’s [Micropub](https://micropub.spec.indieweb.org/) server - all [IndieWeb](https://indieweb.org) technologies.

I have seen [https://github.com/kappa-db/multifeed](https://github.com/kappa-db/multifeed) but I’d like to see something a bit more supported - especially since [https://github.com/kappa-db/multifeed/issues/19](https://github.com/kappa-db/multifeed/issues/19) doesn’t seem to be a feature; something that would be critical to this.

(Originally published at: https://v2.jacky.wtf/post/df01b773-02c7-48e1-8c60-1466d0577a89)

**Comment by RangerMauve** [comment]
@jalcine One thing you could play around with is [multi-hyperdrive](https://github.com/RangerMauve/multi-hyperdrive) which lets you sandwitch a bunch of hyperdrives on top of each other, it's a lot less opinionated than multifeed stuff and works well with sparse replication of metadata (better for huge datasets)

With it you can leave it to your application to figure out where the drives come from and to load them up together.

If you want something a bit higher level, there's [co-hyperdrive](https://github.com/RangerMauve/co-hyperdrive) which builds on top of multi-hyperdrive and stores references to writers within the hyperdrive itself / auto-loads them.

This lets your application decide when to add another writer (can only be done by a peer that's already a writer) and is an eventually consistent system.

These modules work best when you have peers uploading different files which are unlikely to conflict or are changing the same file slowly over time. it's not a good building block for multi-user collaborative editing.

This is being used in the [Natakanu](https://github.com/Wapikoni-Technique/Natakanu) project and is working pretty well for multi-user file sharing.

**Comment by jalcine** [comment]
Oh, this is _sick_. Thank you [@RangerMauve](https://ranger.mauve.moe/) for introducing this to me!

(Originally published at: https://v2.jacky.wtf/post/ab491578-0717-43e9-abf3-4fffa02309ba)

**Comment by raphael10-collab** [comment]
@RangerMauve What do you suggest among the available hyper modules to use for a multi-user collaborative editing?

**Comment by RangerMauve** [comment]
@ralphtheninja Depends on what your data model is like. You might want to look into other things like [y.js](https://docs.yjs.dev/) . Else you can update something like [hypermerge](https://github.com/automerge/hypermerge) which uses CRDTs to represent data.

One worry I have is that a lot of the stuff building on top of hypercore for collaborative editing doesn't use sparse data structures so as your history gets longer it'll get way slower, especially if new users join in. 🤷

**Comment by raphael10-collab** [comment]
@RangerMauve your worry of not using sparse data structures so as my history gets longer it will get way slower, especially if new users join in, is the performance degradation over time issue described in the `pushpin` app which uses `hypermerge` ?

https://github.com/automerge/pushpin/blob/master/WARNINGS.md#performance-may-degrade-over-time

According to you which CRDT's implementation uses sparse data structures, and therefore could mitigate this problem?
https://crdt.tech/implementations
