### ISSUE TITLE
Unable to open hyperdrive v10 with {metadata, content} storage

### ISSUE THREAD

**Issue by okdistribute** [holepunchto/hyperdrive#266]
In v9 and in the README, you used to be able to pass `{metadata: Fn, content: Fn}` as the `storage` parameter. This feature seems to have been lost in hyperdrive v10.

From the README.md:

> If you require complete control, you can also pass in an object containing a metadata and a content field. Both of these need to be functions, and are called with the following arguments:

Is this feature intended to be pulled back in, or will it be deprecated completely in v10?

**Comment by okdistribute** [comment]
also `archive.content` is a missing property, I wonder if this could be related regressions as part of the major corestore refactoring. @andrewosh ?

**Comment by mafintosh** [comment]
passing in metadata and content is not supported as v10 has many metadata and content feeds due to mounts. Same reason why no .content is exposed
