### ISSUE TITLE
Missing NTFS/ReFS sparse support

### ISSUE THREAD

**Issue by da2x** [holepunchto/hyperdrive#267]
[NTFS requires](http://www.ntfs.com/ntfs-sparse.htm) files to be created with the [`FILE_ATTRIBUTE_SPARSE_FILE`](https://docs.microsoft.com/en-us/windows/win32/api/winioctl/ni-winioctl-fsctl_set_sparse) attribute to treat them as sparse. This is different from other modern OSes where you don’t need to do anything special.

I tested with `fsutil.exe sparse queryflag hyperdrive_file_name` and various calls to check file sizes, and found that Hyperdrives aren’t marked as sparse files on NTFS.

Because of this, Hyperdrives downloaded with Dat or Beaker take up the full size of the archive on disk even though it contains huge sections of zero-bytes.

**Comment by mafintosh** [comment]
Excellent find! I’ll try to fix this in the random-access-file module

**Comment by da2x** [comment]
Sorry about reporting against the wrong repo. Should I close this and reopen an issue there?

**Comment by mafintosh** [comment]
If you don’t mind yes. We can keep this one open to track it here also still

**Comment by da2x** [comment]
https://github.com/random-access-storage/random-access-file/issues/23
