### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by talentlessguy** [holepunchto/hyperdrive#313]
Would be great for this package to have Deno support.

At the moment the main blocker is this: 

```
error: Uncaught ReferenceError: require is not defined
    at https://cdn.esm.sh/v41/node-gyp-build@4.2.3/deno/node-gyp-build.js:2:952
```

some dep seems to be using `node-gyp` and it prevents it from working on Deno

**Comment by talentlessguy** [comment]
does it work on deno now? @mafintosh

**Comment by mafintosh** [comment]
Ah, I don't know, don't use Deno, just cleaned all stale issues from here.

**Comment by voidvoxel** [comment]
Still not working on Deno as of writing. Here is the current error message:

```
error: Uncaught (in promise) ReferenceError: require is not defined
const safetyCatch = require('safety-catch')
                    ^
    at https://unpkg.com/corestore@6.18.2/index.js:1:21
```

I'd be happy contribute in any way I can! I'd love to see the Hypercore ecosystem running on Deno :two_hearts:
