### ISSUE TITLE
Provide an API for user defined metadata

### ISSUE THREAD

**Issue by scriptjs** [holepunchto/hyperdrive#69]
To enable broader uses of files in a hyperdrive, it requires an API to enable user defined metadata to be added and extracted from files.

**Comment by substack** [comment]
This feature can be done outside of hyperdrive itself with [hyperdrive-index](https://www.npmjs.com/package/hyperdrive-index). For example, I'm indexing jpeg markers with [hyperdrive-jpeg-index](https://www.npmjs.com/package/hyperdrive-jpeg-index) and soon I'm also going to write thumbnails out into a separate hyperdrive archive.

**Comment by scriptjs** [comment]
Indexes are definitely a good thing. I don't think the addition of this API is that expensive but its really a decision in the end whether or not to implement it.
