### ISSUE TITLE
Restoring files after deletion from the FS

### ISSUE THREAD

**Issue by pfrazee** [holepunchto/hyperdrive#91]
I have a hyperdrive that I don't own. The hyperdrive writes the files to disk using RAF. I downloaded a file in the archive, then deleted it from the FS.

On a subsequent `createFileReadStream` call for the deleted file, I receive the following error:

```
Error: Could not satisfy length
    at onread (/Users/paulfrazee/my/beaker-browser/app/node_modules/random-access-file/index.js:77:27)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:675:17)
```

Would it be possible to recognize this scenario within the code, and attempt to redownload the file?

I think it'd be suitable (maybe best) if redownloading was not automatic, but the choice of the app consuming the hyperdrive API. But, the API will need to give the tools to recognize the condition and handle it.

**Comment by karissa** [comment]
Ah yeah, makes sense. Perhaps expected behavior is that createReadFileStream could try to find the file from a swarm if it couldn't find it on disk..
